- name: ' Configure Keycloak Provider | configure-pvc-expansion.yml'
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    module: "Config PVC Expansion"
    ansible_name_module: "Configure PVC Expansion | {{ module }}"
  pre_tasks:
    - name: Install required pip library
      pip:
        name: openshift
        state: present

    - name: Ensure Proper Python dependency is installed for Openshift
      python_requirements_facts:
        dependencies:
          - openshift
          - requests
    - name: Authenticate with the API
      command: >
        {{ openshift_cli }} login \
          --token {{ ocp_cluster_token }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      when:
        - ocp_cluster_token is defined and ocp_cluster_token != ""
      register: login_out

    - name: Authenticate with the API
      command: >
        {{ openshift_cli }} login \
          -u {{ ocp_cluster_user }} \
          -p {{ ocp_cluster_user_password }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      when:
        - not ocp_cluster_token is defined or ocp_cluster_token == ""
      register: login_out

  tasks:
    - name: '{{ ansible_name_module }} | | get default storage class if not provided'
      when:
        - not storage_class is defined or storage_class == ''
      block:
        - name: '{{ ansible_name_module }} | | get storage class if not provided'
          shell: >
            {{ openshift_cli }} get storageclass --no-headers | grep -i "{{ storage_class_type | d('kubernetes.io/aws-ebs', true) }}" | awk '{print $1}'
          register: default_sc

        - name: '{{ ansible_name_module }} | set_fact | set storage_class'
          set_fact:
            storage_class: "{{ default_sc.stdout }}"
          when:
            - default_sc is defined
            - default_sc.rc is defined
            - default_sc.rc == 0
            - default_sc.stdout is defined
            - default_sc.stdout != ''

    - name: '{{ ansible_name_module }} | command:{{ openshift_cli }} patch | storageclass'
      command: >
        {{ openshift_cli }} patch storageclass {{ storage_class }} --type merge -p '{"allowVolumeExpansion": true}'
      register: storage_class_patched
