- name: ' Configure ODF Cluster | configure-odf-cluster.yml'
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    module: "configure-odf-cluster"
    ansible_name_module: "Configure ODF Cluster | {{ module }}"
  pre_tasks:
    - name: Install required pip library
      pip:
        name: openshift
        state: present

    - name: Ensure Proper Python dependency is installed for Openshift
      python_requirements_facts:
        dependencies:
          - openshift
          - requests
    - name: Authenticate with the API
      command: >
        {{ openshift_cli }} login \
          --token {{ ocp_cluster_token }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      when:
        - ocp_cluster_token is defined and ocp_cluster_token != ""
      register: login_out

    - name: Authenticate with the API
      command: >
        {{ openshift_cli }} login \
          -u {{ ocp_cluster_user }} \
          -p {{ ocp_cluster_user_password }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      when:
        - not ocp_cluster_token is defined or ocp_cluster_token == ""
      register: login_out

  tasks:
    - name: '{{ ansible_name_module }} | include_tasks | Import additional ODF operator install check tasks'
      ansible.builtin.include_tasks: tasks/ensure-odf-operator-is-installed.yml
      vars:
        odf_ns: "{{ odf_operator.deploy_namespace }}"

    - name: '{{ ansible_name_module }} | include_tasks | Import additional ODF validation check tasks'
      ansible.builtin.include_tasks: tasks/ensure-odf-nodes-exist.yml

    - name: '{{ ansible_name_module }} | include_tasks | Import additional ODF Cluster config tasks'
      ansible.builtin.include_tasks: tasks/configure-odf-cluster.yml
      vars:
        apply_odf_cluster: 'true'
        odf_cluster_cr_template: '../templates/odf-cluster-customresource.yml.j2'
        odf_device_block_size: "{{ odf_operator.device_block_size }}"
        odf_storage_class: "{{ odf_operator.storage_class }}"
        odf_device_volume_mode: "{{ odf_operator.device_volume_mode }}"
        odf_node_count: "{{ odf_nodes_count }}"
        apply_missing_sc: 'true'
      when:
        - odf_nodes_count is defined
        - odf_nodes_count | int >= 3

    - name: '{{ ansible_name_module }} | include_tasks | Import additional ODF OBC PV backingstore config tasks'
      ansible.builtin.include_tasks: tasks/configure-odf-noobaa-pvbackingstore.yml
      when:
        - enable_pvbackingstore_obc is defined
        - enable_pvbackingstore_obc | bool

    - name: '{{ ansible_name_module }} | include_tasks | Import additional ODF RGW Object store config tasks'
      ansible.builtin.include_tasks: tasks/configure-odf-rgw-cephstore.yml
      when:
        - enable_rgw_object_store_obc is defined
        - enable_rgw_object_store_obc | bool

    - name: '{{ ansible_name_module }} | include_tasks | Import additional ODF RGW backingstore config tasks'
      ansible.builtin.include_tasks: tasks/configure-odf-rgw-backingstore.yml
      when:
        - enable_rgw_backingstore is defined
        - enable_rgw_backingstore | bool

