- name: ' Configure Keycloak Provider | configure-keycloak-provider.yml'
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    module: "Config keycloak provider"
    ansible_name_module: "Configure Keycloak Provider | {{ module }}"
  pre_tasks:
    - name: Install required pip library
      pip:
        name: openshift
        state: present

    - name: Ensure Proper Python dependency is installed for Openshift
      python_requirements_facts:
        dependencies:
          - openshift
          - requests
    - name: Authenticate with the API
      command: >
        {{ openshift_cli }} login \
          --token {{ ocp_cluster_token }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      when:
        - ocp_cluster_token is defined and ocp_cluster_token != ""
      register: login_out

    - name: Authenticate with the API
      command: >
        {{ openshift_cli }} login \
          -u {{ ocp_cluster_user }} \
          -p {{ ocp_cluster_user_password }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      when:
        - not ocp_cluster_token is defined or ocp_cluster_token == ""
      register: login_out
  tasks:
    - name: '{{ ansible_name_module }} Config keycloak CA'
      import_role:
        name: copy-user-ca-bundle-cm-into-new-ca-bundle
      vars:
        existing_ca_cm_name: "{{ keycloak_ca_cm_name }}"
        new_ca_cm_name: "{{ keycloak_ca_cm_name }}"
        new_ca_bundle_cm_file: "{{ keycloak_ca_cm_file }}"
        existing_ca_bundle_cm_namespace: "openshift-config"
        new_ca_bundle_cm_namespace: "openshift-config"
        create_new_ca_bundle_cm: 'true'  
      when:
        - use_keycloak_ca is defined
        - use_keycloak_ca | bool
        - keycloak_ca_cm_name is defined
        - keycloak_ca_cm_name != '' 
        - keycloak_ca_cm_file is defined
        - keycloak_ca_cm_file != '' 

    - name: '{{ ansible_name_module }} | command:{{ openshift_cli }} | create secret'
      command: >
        {{ openshift_cli }} create secret generic {{ keycloak_secret_name }} --from-literal=clientSecret={{ keycloak_secret }} -n openshift-config"
      register: keycloak_secret_created

    - name: '{{ ansible_name_module }} | template | Copy Infranode machineset template to staging location'
      template:
        src: "templates/oauth-cr.yml.j2"
        dest: "{{ staging_dir | d('/tmp', true) }}/oauth-cr.yml"
      register: oauth_cr_file_created

    - name: '{{ ansible_name_module }} | command:{{ openshift_cli }} | create secret'
      command: >
        {{ openshift_cli }} apply -f {{ staging_dir | d('/tmp', true) }}/oauth-cr.yml
      register: oauth_cr_updated
