#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' install-and-configure-operators-from-olm.yml' 
  hosts: localhost 
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    module: "configure-and-install-operators-from-disconnected-OLM"
    ansible_name_module: " Deploy Operator from OLM | {{ module }}"
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'

  tasks:
    - name: Install required pip library
      pip:
        name: openshift
        state: present

    - name: Ensure Proper Python dependency is installed for Openshift
      python_requirements_facts:
        dependencies:
          - openshift
          - requests

    - name: Authenticate with the API
      command: >
        {{ openshift_cli }} login \
          -u {{ ocp_cluster_user }} \
          -p {{ ocp_cluster_user_password }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      register: login_out
      
    - name: Configure Disconnected OLM 
      import_role:
        name: config-disconnected-olm 
      vars:
        ocp_cluster_admin_user: '{{ ocp_cluster_user }}'
        ocp_cluster_admin_password: '{{ ocp_cluster_user_password }}'
        ocp_cluster_console_url: '{{ ocp_cluster_console_url }}'
        ocp_cluster_console_port: '{{ ocp_cluster_console_port }}'
        ansible_name_module: 'Configure disconnected OLM'
      when:
        - configure_disconnected_OLM is defined
        - configure_disconnected_OLM | bool 

    - name: Overwrite operator_to_deploy variable if necessary 
      set_fact:
        operators_to_deploy: "{{ operators_to_deploy_single_index }}"
      when:
        - use_single_index_per_operator is defined
        - use_single_index_per_operator | bool

    - name: Deploy operators from OLM
      import_role:
        name: deploy-operators-from-olm 

