- name: 'Configure STS for components needing STS | post-deploy-configure-ocp-credentials-for-components-needing-aws-sts.yml'
  hosts: localhost
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
    - 'vars/cluster.yml'
    - 'vars/fabric.yml'
    - 'vars/observability.yml'
  vars:
    module: "Configure AWS Credentials "
    ansible_name_module: " Post Cluster Installation | {{ module }}"

  pre_tasks:
    - name: '{{ ansible_name_module }} | ansible.builtin.assert | validate ocp_comp_sts_to_configure'
      ansible.builtin.assert:
        that:
          - ocp_comp_sts_to_configure is defined 
          - ocp_comp_sts_to_configure != ""
          - ocp_comp_sts_to_configure is mapping 
          - ocp_comp_sts_to_configure.keys() is defined 
          - ocp_comp_sts_to_configure.keys() | length > 0
        msg: " the ocp_comp_sts_to_configure must be defined "

    - name: Ensure Proper Python dependency is installed for Openshift
      community.general.python_requirements_info:
        dependencies:
          - openshift
          - requests

    - name: Authenticate with the API
      ansible.builtin.command: >
        {{ openshift_cli }} login \
          --token {{ ocp_cluster_token }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      when:
        - ocp_cluster_token is defined and ocp_cluster_token != ""
      register: login_out

    - name: Authenticate with the API
      ansible.builtin.command: >
        {{ openshift_cli }} login \
          -u {{ ocp_cluster_user }} \
          -p {{ ocp_cluster_user_password }} \
          --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
      when:
        - not ocp_cluster_token is defined or ocp_cluster_token == ""
      register: login_out

  tasks:
    - name: '{{ ansible_name_module }} | set_fact | Set openshift_sts_policy_docs_file_dir'
      ansible.builtin.set_fact:
        ocp_comp_sts_policy_docs_file_dir: "{{ staging_dir }}/{{cluster_name }}/ocp-sts-iam-policy-docs"
    
    - name: '{{ ansible_name_module }} | set_fact | Set ocp_comp_ccoctl_sts_policy_docs_file_dir'
      ansible.builtin.set_fact:
        ocp_comp_ccoctl_sts_policy_docs_file_dir: "{{ staging_dir }}/{{cluster_name }}/ccoctl-sts-iam-policy-docs"
      when:
        - not ocp_comp_ccoctl_sts_policy_docs_file_dir is defined or ocp_comp_ccoctl_sts_policy_docs_file_dir == ""

    - name: '{{ ansible_name_module }} | set_fact | cloud_cred_manifests_dir '
      ansible.builtin.set_fact:
        cloud_cred_manifests_dir: "{{ staging_dir }}/{{cluster_name }}/ccoctl-cloud-creds-manifests"
    
    - name: '{{ ansible_name_module }} | ansible.builtin.file | Ensure the staging dir exist '
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0777
      loop:
        - "{{ ocp_comp_sts_policy_docs_file_dir }}"
        - "{{ ocp_comp_ccoctl_sts_policy_docs_file_dir }}"
        - "{{ cloud_cred_manifests_dir }}"

    - name: '{{ ansible_name_module }} | Include OCP STS component config tasks'
      ansible.builtin.include_tasks: tasks/configure-ocp-component-sts-iam-policy-and-cloud-creds.yml
      with_dict: "{{ ocp_comp_sts_to_configure }}"
      loop_control:
        index_var: key_cnt 
      when:
        - item.key is defined and item.key != ""
        - item.value.name is defined and item.value.name != ""
        - item.value.namespace is defined and item.value.namespace != ""
        - item.value.service_accounts is defined and item.value.service_accounts != ""
        - item.value.iam_perms_policy_doc_file is defined and item.value.iam_perms_policy_doc_file != ""
        - not item.value.use_ccoctl is defined or not item.value.use_ccoctl | bool
      vars:
        ocp_comp_ns: "{{ item.value.namespace }}"
        ocp_comp_sa_list: "{{ item.value.service_accounts }}"
        ocp_comp_name: "{{ item.value.name }}"
        ocp_comp_iam_role_name: "{{ item.value.iam_role_name if item.value.iam_role_name is defined and item.value.iam_role_name != '' else (cluster_name + '-openshift-' + item.value.name) }}"
        ocp_comp_sts_policy_doc_file_template: "{{ item.value.iam_perms_policy_doc_file }}"
        ocp_comp_aws_cloud_creds_secret_name: "{{ item.value.aws_cloud_cred_secret_name }}"
      register: ocp_comp_sts_configured

    - name: '{{ ansible_name_module }} | Include OCP STS component config tasks'
      ansible.builtin.include_tasks: tasks/configure-ocp-component-sts-iam-policy-and-cloud-creds-using-ccoctl.yml
      with_dict: "{{ ocp_comp_sts_to_configure }}"
      loop_control:
        index_var: key_cnt 
      when:
        - item.key is defined and item.key != ""
        - item.value.name is defined and item.value.name != ""
        - item.value.namespace is defined and item.value.namespace != ""
        - item.value.service_accounts is defined and item.value.service_accounts != ""
        - item.value.aws_service_perms is defined and item.value.aws_service_perms != ""
        - item.value.use_ccoctl is defined and item.value.use_ccoctl | bool
        - item.value.aws_cloud_cred_secret_name is defined and item.value.aws_cloud_cred_secret_name != ""
      vars:
        ocp_comp_ns: "{{ item.value.namespace }}"
        ocp_comp_sa_list: "{{ item.value.service_accounts }}"
        ocp_comp_name: "{{ item.value.name }}"
        ocp_comp_aws_service_perms: "{{ item.value.aws_service_perms }}"
        ocp_comp_aws_cloud_creds_secret_name: "{{ item.value.aws_cloud_cred_secret_name }}"
      register: ocp_comp_sts_configured

    - name: '{{ ansible_name_module }} | apply IAM role secret manifests tasks'
      ansible.builtin.include_tasks: tasks/apply-ccoctl-iam-roles-secret-manifests.yml
      vars:
        ccoctl_manifests_dir: '{{ ocp_comp_ccoctl_sts_policy_docs_file_dir }}'

    - name: '{{ ansible_name_module }} | apply IAM role credentialsrequest  manifests tasks'
      ansible.builtin.include_tasks: tasks/apply-ccoctl-iam-roles-credentialsrequest-manifests.yml

