- name: ' Konductor | Provision UPI Infra | uninstall-olm-operators.yml'
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    module: "remove deployed operators from OLM"
    ansible_name_module: " Post Cluster Installation | Remove deployed Operators | {{ module }}"
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'

  pre_tasks:
    - name: '{{ ansible_name_module }} | import_role | OCP cluster login'
      import_role:
        name: ocp-cluster-login

  tasks:
    - name: '{{ ansible_name_module }} | get all OperatorGroup'
      shell: >
        {{ openshift_cli }} get og --all-namespaces --no-headers | awk '{print $2 " -n " $1}' 
      register: all_ogs

    - name: '{{ ansible_name_module }} | delete all OperatorGroup objects'
      command: >
        {{ openshift_cli }} delete og {{ item }}
      loop: "{{ all_ogs.stdout_lines }}" 
      when:
        - "not 'olm-operators' in item"
        - "not 'global-operators' in item"
      register: deleted_ogs

    - name: '{{ ansible_name_module }} | get all Subscriptions'
      shell: >
        {{ openshift_cli }} get sub -A --no-headers | awk '{print $2 " -n " $1}' 
      register: all_subs

    - name: '{{ ansible_name_module }} | delete all Subscription objects'
      command: >
        {{ openshift_cli }} delete sub {{ item }}
      loop: "{{ all_subs.stdout_lines }}" 
      when:
        - "not 'olm-operators' in item"
        - "not 'global-operators' in item"
      register: deleted_subs

    - name: '{{ ansible_name_module }} | get all job in the openshift-marketplace'
      shell: >
        {{ openshift_cli }} get job.batch -n openshift-marketplace --no-headers | awk '{print $1 " -n openshift-marketplace "}' 
      register: all_opjobs

    - name: '{{ ansible_name_module }} | delete all job objects from openshift-marketplace'
      command: >
        {{ openshift_cli }} delete job.batch {{ item }} --cascade
      loop: "{{ all_opjobs.stdout_lines }}" 
      when:
        - "not 'olm-operators' in item"
        - "not 'global-operators' in item"
      register: deleted_opjobs
