---
#######  find AWS IAM role credenialsrequest manifest to apply
- name: '{{ ansible_name_module }} | find |  Find all IAM role credentialsrequest manifest files'
  ansible.builtin.find:
    path: "{{ cloud_cred_manifests_dir }}/manifests"
    recurse: yes
    patterns: "*-credential-request.yaml"
  register: iam_role_cred_request_manifests

- name: '{{ ansible_name_module }} | set_fact | iam_role_credreq_manifests_paths file paths'
  ansible.builtin.set_fact:
    iam_role_credreq_manifests_paths: "{{ iam_role_cred_request_manifests.files | map(attribute='path') | list }}"
  when:
    - iam_role_cred_request_manifests is defined
    - iam_role_cred_request_manifests.files is defined
    - iam_role_cred_request_manifests.files | length > 0

- name: '{{ ansible_name_module }} | Apply ocp comp aws creds request manifests'
  ansible.builtin.command: >
    {{ openshift_cli }} apply -f {{ item }}
  loop: "{{ iam_role_credreq_manifests_paths }}"
  when:
    - iam_role_credreq_manifests_paths is defined
    - iam_role_credreq_manifests_paths | default([], true) | length > 0 
  register: ocp_comp_aws_cloud_cred_applied

