---
#######  find AWS IAM role cred secret manifest to apply
- name: '{{ ansible_name_module }} | find |  Find all IAM role manifest files'
  ansible.builtin.find:
    path: "{{ ccoctl_manifests_dir }}/manifests"
    recurse: yes
    patterns: "*-credentials.yaml"
  register: iam_role_cred_secret_manifests

- name: '{{ ansible_name_module }} | set_fact | iam_role_manifests_paths file paths'
  ansible.builtin.set_fact:
    iam_role_manifests_paths: "{{ iam_role_cred_secret_manifests.files | map(attribute='path') | list }}"
  when:
    - iam_role_cred_secret_manifests is defined
    - iam_role_cred_secret_manifests.files is defined
    - iam_role_cred_secret_manifests.files | length > 0

- name: '{{ ansible_name_module }} | Apply ocp comp aws cloud creds'
  ansible.builtin.command: >
    {{ openshift_cli }} apply -f {{ item }}
  loop: "{{ iam_role_manifests_paths }}"
  when:
    - iam_role_manifests_paths is defined
    - iam_role_manifests_paths | default([], true) | length > 0 
  register: ocp_comp_aws_cloud_cred_applied

