- name: '{{ ansible_name_module }} | create  loki s3  secret'
  ansible.builtin.shell: >
    {{ openshift_cli }} create secret generic {{ cluster_logging_storage_s3_secret }} \
       --from-literal=access_key_id={{ aws_access_key }} \
       --from-literal=access_key_secret={{ aws_access_secret }} \
       --from-literal=bucketnames={{ bucket_name }} \
       --from-literal=endpoint={{ aws_s3_endpoint  }} \
       --from-literal=region={{ aws_region }} \
       --from-literal=forcepathstyle='true' \
       -n {{ bucket_namespace }} --dry-run=client -o yaml \
       | oc replace -f - --force

  register: loki_s3_secret_created
  no_log: true

#- name: '{{ ansible_name_module }} | Create Thanos s3  secret'
#  when:
#    - is_hub_cluster is defined
#    - is_hub_cluster | bool 
#  block:
#    - name: '{{ ansible_name_module }} | set thanos s3 endpoint for aws if applicable' 
#      ansible.builtin.set_fact:
#        thanos_bucket_endpoint: "{{ ((aws_svc_endpoints | selectattr('name', 'equalto', 's3') | map(attribute='url') | list).0).split('https://')[1] }}{{ ':80' if thanos_bucket_insecure is defined and thanos_bucket_insecure | bool else ':443' }}"
#      when:
#        - not thanos_bucket_endpoint is defined or thanos_bucket_endpoint == ''
#        - is_aws_environment | bool

#    - name: '{{ ansible_name_module }} | template | Render ACM thanos S3 config secret to staging location'
#      ansible.builtin.template:
#        src: "{{ thanos_s3_secret_config_template }}"
#        dest: "{{ staging_dir }}/{{ (thanos_s3_secret_config_template | basename).split('.j2')[0] }}"
#        force: yes
#      register: thanos_s3_secret_config_rendered

#    - name: '{{ ansible_name_module }} | create  thanos s3  secret'
#      ansible.builtin.shell: >
#        {{ openshift_cli }} get namespace {{ acm_monitoring_namespace }} 
#      ignore_errors: true
#      register: acm_monitoring_namespace_exist

#    - name: '{{ ansible_name_module }} | assert | the acm_monitoring_namespace is defined'
#      ansible.builtin.assert:
#        that:
#          - acm_monitoring_namespace_exist is defined
#          - acm_monitoring_namespace_exist.rc is defined
#          - acm_monitoring_namespace_exist.rc == 0 
#          - acm_monitoring_namespace_exist.stdout is defined
#          - acm_monitoring_namespace_exist.stdout != ''
#          - acm_monitoring_namespace in acm_monitoring_namespace_exist.stdout
#        msg: "The acm_monitoring_namespace is required to create the thanos S3 bucket"

#    - name: '{{ ansible_name_module }} | create  thanos s3  secret'
#      ansible.builtin.shell: >
#        {{ openshift_cli }} create secret generic {{ acm_thanos_storage_s3_secret }} \
#           --from-file=thanos.yaml={{ thanos_s3_secret_config_rendered.dest }} \
#           -n {{ acm_monitoring_namespace }} \
#           --dry-run=client -o yaml \
#           | {{ openshift_cli }} replace --force -f - 
#      when:
#        - thanos_s3_secret_config_rendered is defined
#        - thanos_s3_secret_config_rendered.dest is defined
#        - thanos_s3_secret_config_rendered.dest != '' 
#      register: thanos_s3_secret_created

- name: "Run AWS bucket creation logic"
  when: is_aws_environment | default(false) | bool
  block:
    - name: '{{ ansible_name_module }} | Import AWS S3 CA CM tasks'
      ansible.builtin.include_tasks: tasks/create-aws-s3-cm.yml 
      vars:
        s3_bucket_tls_ca_cm: '{{ cluster_logging_storage_tls_ca_cm }}'

- name: "Run AWS bucket creation logic"
  when: 
    - not is_aws_environment is defined or not is_aws_environment | bool 
  block:
    - name: '{{ ansible_name_module }} |Retrieve existing ConfigMap CM'
      ansible.builtin.command: >
        {{ openshift_cli }} get configmap {{ cluster_logging_storage_tls_ca_cm }} -n {{ bucket_namespace }}
      ignore_errors: yes
      register: logging_storage_ca_cm_exist

    - name: '{{ ansible_name_module }} | Delete Existing logging storage cm'
      ansible.builtin.command: >
        {{ openshift_cli }} delete configmap {{ cluster_logging_storage_tls_ca_cm }} -n {{ bucket_namespace }}
      ignore_errors: yes
      when:
        - logging_storage_ca_cm_exist.rc is defined
        - logging_storage_ca_cm_exist.rc == 0
      register: logging_storage_ca_cm_deleted

    - name: '{{ ansible_name_module }} | Creat CA logging storage CM using user-ca-bundle CM'
      ansible.builtin.include_tasks: ../roles/copy-user-ca-bundle-cm-into-new-ca-bundle/tasks/main.yml 
      vars:
        existing_ca_bundle_cm_name: 'user-ca-bundle'
        existing_ca_bundle_cm_namespace: 'openshift-config'
        new_ca_bundle_cm_name: '{{ cluster_logging_storage_tls_ca_cm }}'
        new_ca_bundle_cm_file: '{{ staging_dir }}/cluster-logging-storage-ca.yaml'
        new_ca_bundle_cm_namespace: '{{ bucket_namespace }}'
        new_ca_bundle_cert_key: "{{ cluster_logging_storage_tls_ca_cm_key | default('ca.crt', true) }}"
        create_new_ca_bundle_cm: 'true'
        update_new_ca_bundle_cm_namespace: 'true'
      register: logging_storage_ca_cm_created

#- name: "Run On-Premis (RGW) Deployment Logic"
#  when: 
#    - not is_aws_environment | bool
#    - not minio_required | bool
#  block:
#    - name: "Import s3 bucket creation playbook for RGW"
#      ansible.builtin.include_tasks: tasks/create-rgw-obc-on-odf-cluster.yml 
#      vars:
#        rgw_bucket_namespace : "{{ bucket_namespace }}"
#        rgw_bucket_name: "{{ bucket_name }}"
#      register: s3_bucket_created

#    - name: "Import s3 bucket info tasks"
#      ansible.builtin.include_tasks: tasks/retrieve-obc-credentials-from-odf-cluster.yml
#      vars:
#        bucket_namespace : "{{ bucket_namespace }}"
#        bucket_name: "{{ bucket_name }}"
#        bucket_cluster_console_url: "{{ cluster_logging_obc_bucket_cluster_console_url }}"
#        bucket_cluster_token: ""  ### These two are mutually exclusive.
#        skip_api_login_logout: "false" ### set to true if S3 is within the same cluster

# # --- PLACEHOLDER BLOCK FOR MINIO? HYPOTHETICAL CODE BELOW!!!
# - name: Fetch rgw bucket secret needed for lokistack-logging-obc secret
#   kubernetes.core.k8s_info:
#     api_version: v1
#     validate_certs: false
#     kind: Secret
#     name: "{{ obc_bucket_name }}"
#     namespace: "{{ obc_bucket_namespace }}"
#   register: minio_bucket_secret
#   no_log: true
#   when: minio_required | default(false) | bool

# - amazon.aws.s3_bucket:
#   name: mys3bucket
#   endpoint_url: http://minio.endpoint.url.goes.here
#   aws_access_key: "{{ minio_bucket_secret.resources[0].data.AWS_ACCESS_KEY_ID | b64decode }}"
#   aws_secret_key: "{{ minio_bucket_secret.resources[0].data.AWS_SECRET_ACCESS_KEY | b64decode }}"
#   ceph: true
#   when: minio_required | default(false) | bool
#    register: s3_bucket_created

